### PR TITLE
#97 Remove Travis CI

### PR DESCRIPTION
**Pull request by 3rdvision**
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/products/issues/97 |
| Decisions | - Remove Travis CI |

### CODE REVIEW

**Review by NFSS10 — APPROVED** [review]
@3rdvision Don't forget the labels

**Comment by 3rdvision** [comment]
> @3rdvision Don't forget the labels

Couldn't find one that fits

**Comment by 3rdvision** [comment]
@hugo-gomes assigning you because I have no permissions to merge this one

**Comment by hugo-gomes** [comment]
@3rdvision send a request to tech-requests@platforme.com asking to review the permissions setup of this repo

**Review by hugo-gomes — APPROVED** [review]

**Pull request merged**
